language: perl

matrix:
  include:
    - perl: "5.20"
      dist: trusty
    - perl: "5.22"
    - perl: "5.26"
    - perl: "5.30"

env:
    - TEST_ALL=1

cache:
  directories:
    - $HOME/perl5

install:
  - cpanm -n --quiet --installdeps --with-develop .

after_success:
  - cover -test -report coveralls
  - cover -test -report kritika
