=encoding utf8

=begin html

<a href="https://travis-ci.com/kiwiroy/mojolicious-command-author-generate-launchd">
  <img alt="Build Status"
       src="https://travis-ci.com/kiwiroy/mojolicious-command-author-generate-launchd.svg?token=Kpqpmk91fYg5k9hdqK3y&branch=master">
</a>
<a href="https://coveralls.io/github/kiwiroy/mojolicious-command-author-generate-launchd?branch=master">
  <img alt="Coverage Status"
       src="https://coveralls.io/repos/github/kiwiroy/mojolicious-command-author-generate-launchd/badge.svg?branch=master" />
</a>
<a href="https://kritika.io/users/kiwiroy/repos/9828314644594857/heads/master/">
  <img alt="Kritika Analysis Status"
       src="https://kritika.io/users/kiwiroy/repos/9828314644594857/heads/master/status.svg?type=score%2Bcoverage%2Bdeps" />
</a>

=end html

=head1 NAME

hypnotoad-launchd - Hypnotoad HTTP and WebSocket server managed by launchd

=head1 SYNOPSIS

  Usage: hypnotoad-launchd [OPTIONS] [APPLICATION]

    hypnotoad-launchd ./script/my_app
    hypnotoad-launchd ./myapp.pl
    hypnotoad-launchd -s ./myapp.pl
    hypnotoad-launchd -t ./myapp.pl

  Options:
    -h, --help         Show this message
    -a, --auto         Enable the autorestarting feature (not supported)
    -s, --stop         Stop server gracefully
    -t, --test         Test application and exit

=head1 DESCRIPTION

Start L<Mojolicious> and L<Mojolicious::Lite> applications with the
L<Hypnotoad|Mojo::Server::Hypnotoad> web server in a method that is managed by
C<launchd>/C<launchctl>.

Essentially, this is a controller script for C<hypnotoad> that runs in the
foreground utilising the code from L<Mojo::Server::Hypnotoad> and
L<Mojo::Server::Prefork>. Identical signals are handled and proxied to the
daemonized instance of C<hypnotoad> as required.

=head1 SEE ALSO

L<Mojolicious>, L<Mojolicious::Guides>, L<https://mojolicious.org>, L<daemondo|https://github.com/macports/macports-base/blob/master/src/programs/daemondo/main.c> from macports.


=cut

